image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - cd client

stages:
  - build
  - lint

build:
  stage: build
  script:
    - npm ci
    - npm run build
    - mv public public-source
    - mv dist public
  artifacts:
    paths:
      - client/public

lint:
  stage: lint
  script:
    - npm i
    - npm run lint --no-fix
