image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - lint

build:
  stage: build
  script:
    - npm ci
    - npm run build
    - mv public public-source
    - mv dist public
  artifacts:
    paths:
      - public

lint:
  stage: tslint
  script:
    - npm i
    - npm run lint

lint:
  stage: prettier
  script:
    - npm i
    - npm run check:format