image: node:latest

stages:
  - build
  - test
  - lint

build-core:
  stage: build
  script:
    - cd core
    - npm ci
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - client/public

build-client:
  stage: build
  script:
    - cd core
    - npm i
    - npm run build
    - cd ../client
    - npm ci
    - npm run build
    - mv public public-source
    - mv dist public
  artifacts:
    paths:
      - client/public

build-server:
  stage: build
  script:
    - cd core
    - npm i
    - npm run build
    - cd ../server
    - npm ci
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - server/public

test-core:
  stage: test
  script:
    - cd core
    - npm i
    - npm run test

test-server:
  stage: test
  script:
    - cd server
    - npm i
    - npm run test

lint-core:
  stage: lint
  script:
    - cd core
    - npm i
    - npm run lint:check
    - npm run format:check

lint-client:
  stage: lint
  script:
    - cd client
    - npm i
    - npm run lint --no-fix

lint-server:
  stage: lint
  script:
    - cd server
    - npm i
    - npm run lint:check
    - npm run format:check
